set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports busy]
set_property IOSTANDARD LVCMOS33 [get_ports clk_c]
set_property IOSTANDARD LVCMOS33 [get_ports rst_c]
set_property IOSTANDARD LVCMOS33 [get_ports start_c]
set_property IOSTANDARD LVCMOS33 [get_ports start_status]
set_property IOSTANDARD LVCMOS33 [get_ports rst_status]

set_property PACKAGE_PIN J15 [get_ports {x[0]}]
set_property PACKAGE_PIN L16 [get_ports {x[1]}]
set_property PACKAGE_PIN M13 [get_ports {x[2]}]
set_property PACKAGE_PIN R15 [get_ports {x[3]}]
set_property PACKAGE_PIN R17 [get_ports {x[4]}]
set_property PACKAGE_PIN T18 [get_ports {x[5]}]
set_property PACKAGE_PIN U18 [get_ports {x[6]}]
set_property PACKAGE_PIN R13 [get_ports {x[7]}]

set_property PACKAGE_PIN H17 [get_ports {result[0]}]
set_property PACKAGE_PIN K15 [get_ports {result[1]}]
set_property PACKAGE_PIN J13 [get_ports {result[2]}]
set_property PACKAGE_PIN N14 [get_ports {result[3]}]
set_property PACKAGE_PIN R18 [get_ports {result[4]}]
set_property PACKAGE_PIN V17 [get_ports {result[5]}]
set_property PACKAGE_PIN U17 [get_ports {result[6]}]
set_property PACKAGE_PIN U16 [get_ports {result[7]}]

set_property PACKAGE_PIN V11 [get_ports {rst_status}]
set_property PACKAGE_PIN V12 [get_ports {start_status}]

set_property PACKAGE_PIN P17 [get_ports start_c]
set_property PACKAGE_PIN E3 [get_ports clk_c]
create_clock -add -name clk_c -period 10.00 -waveform {0.000 5.000} [get_ports clk_c];
set_property PACKAGE_PIN P18 [get_ports rst_c]
set_property PACKAGE_PIN N16 [get_ports busy]
